# Generated by Django 5.2.10 on 2026-02-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ученая степень'),
        ),
        migrations.AddField(
            model_name='user',
            name='academic_title',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ученое звание'),
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(blank=True, max_length=300, verbose_name='Организация'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Участник'), ('reviewer', 'Рецензент'), ('moderator', 'Модератор'), ('admin', 'Администратор конференции'), ('super_admin', 'Супер-администратор')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
