version: "3.8"

services:
  backend:
    build: .
    restart: unless-stopped
    volumes:
      - sqlite_data:/app/db          # Том для базы данных
      - media_data:/app/media         # Том для загруженных файлов
      - static_data:/app/staticfiles  # Том для статических файлов
      - backup_data:/app/db_backups   # Том для резервных копий
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  sqlite_data:        # Именованный том для SQLite
  media_data:         # Именованный том для медиафайлов
  static_data:        # Именованный том для статики
  backup_data:        # Именованный том для бэкапов
