# Generated by Django 5.2.10 on 2026-02-18 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConferenceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='IT-Весна 2026', max_length=200, verbose_name='Название конференции')),
                ('subtitle', models.CharField(default='Студенческая научно-техническая конференция', max_length=300, verbose_name='Подзаголовок')),
                ('description', models.TextField(default='Ежегодная студенческая конференция для молодых исследователей...', max_length=1000, verbose_name='Описание')),
                ('start_date', models.DateField(default=datetime.date(2026, 5, 15), verbose_name='Дата начала')),
                ('end_date', models.DateField(default=datetime.date(2026, 5, 17), verbose_name='Дата окончания')),
                ('location', models.CharField(default='Главный корпус ОГУ', max_length=200, verbose_name='Место проведения')),
                ('submission_deadline', models.DateField(default=datetime.date(2026, 4, 1), verbose_name='Дедлайн подачи тезисов')),
                ('notification_date', models.DateField(default=datetime.date(2026, 4, 15), verbose_name='Дата уведомления о принятии')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Информация о конференции',
                'verbose_name_plural': 'Информация о конференции',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Телефон'), ('address', 'Адрес'), ('social', 'Социальная сеть'), ('other', 'Другое')], max_length=20, verbose_name='Тип контакта')),
                ('title', models.CharField(help_text='Например: "Оргкомитет", "Техническая поддержка"', max_length=100, verbose_name='Название')),
                ('value', models.CharField(max_length=200, verbose_name='Значение')),
                ('icon', models.CharField(blank=True, help_text='Класс иконки (например: bi-envelope, bi-telephone)', max_length=50, verbose_name='Иконка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['order', 'contact_type'],
            },
        ),
        migrations.CreateModel(
            name='ImportantDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название события')),
                ('date', models.DateField(verbose_name='Дата')),
                ('description', models.CharField(blank=True, max_length=300, verbose_name='Описание')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Важная дата',
                'verbose_name_plural': 'Важные даты',
                'ordering': ['order', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='Описание')),
                ('website', models.URLField(blank=True, verbose_name='Сайт')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Организатор',
                'verbose_name_plural': 'Организаторы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UsefulLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Ссылка')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
            ],
            options={
                'verbose_name': 'Полезная ссылка',
                'verbose_name_plural': 'Полезные ссылки',
                'ordering': ['order', 'title'],
            },
        ),
    ]
