# Generated by Django 5.2.10 on 2026-02-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='icon',
        ),
        migrations.AddField(
            model_name='contact',
            name='icon_bootstrap',
            field=models.CharField(blank=True, help_text='Класс иконки (например: bi-envelope, bi-telephone)', max_length=50, verbose_name='Bootstrap иконка'),
        ),
        migrations.AddField(
            model_name='contact',
            name='icon_fallback',
            field=models.ImageField(blank=True, help_text='Изображение, которое покажется, если не загрузится иконка по ссылке', null=True, upload_to='contacts/fallback/', verbose_name='Запасная иконка'),
        ),
        migrations.AddField(
            model_name='contact',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для иконки (рекомендуемый размер: 100x100px)', null=True, upload_to='contacts/icons/', verbose_name='Иконка (изображение)'),
        ),
        migrations.AddField(
            model_name='contact',
            name='icon_type',
            field=models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('image', 'Загруженное изображение'), ('url', 'Ссылка на изображение')], default='bootstrap', max_length=20, verbose_name='Тип иконки'),
        ),
        migrations.AddField(
            model_name='contact',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL изображения для иконки (например, с Gravatar или другого сервиса)', max_length=500, verbose_name='Ссылка на иконку'),
        ),
    ]
