# Generated by Django 5.2.10 on 2026-02-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_contact_icon_contact_icon_bootstrap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizer',
            name='icon_bootstrap',
            field=models.CharField(blank=True, help_text='Класс иконки (например: bi-building, bi-people)', max_length=50, verbose_name='Bootstrap иконка'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='icon_fallback',
            field=models.ImageField(blank=True, help_text='Изображение, которое покажется, если не загрузится иконка по ссылке', null=True, upload_to='organizers/fallback/', verbose_name='Запасная иконка'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Загрузите изображение для иконки (рекомендуемый размер: 200x200px)', null=True, upload_to='organizers/icons/', verbose_name='Иконка (изображение)'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='icon_type',
            field=models.CharField(choices=[('bootstrap', 'Bootstrap Icon'), ('image', 'Загруженное изображение'), ('url', 'Ссылка на изображение')], default='bootstrap', max_length=20, verbose_name='Тип иконки'),
        ),
        migrations.AddField(
            model_name='organizer',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL изображения для иконки (например, логотип организации)', max_length=500, verbose_name='Ссылка на иконку'),
        ),
    ]
