# Generated by Django 5.2.10 on 2026-02-01 15:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('organization', models.CharField(blank=True, max_length=300, verbose_name='Организация')),
                ('department', models.CharField(blank=True, max_length=200, verbose_name='Кафедра/факультет')),
                ('academic_degree', models.CharField(blank=True, max_length=100, verbose_name='Ученая степень')),
                ('academic_title', models.CharField(blank=True, max_length=100, verbose_name='Ученое звание')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('orcid', models.CharField(blank=True, max_length=50, verbose_name='ORCID ID')),
                ('scopus_id', models.CharField(blank=True, max_length=50, verbose_name='Scopus Author ID')),
                ('researcher_id', models.CharField(blank=True, max_length=50, verbose_name='ResearcherID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Авторы',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='AuthorReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок в списке авторов')),
                ('is_main_author', models.BooleanField(default=False, verbose_name='Основной автор')),
                ('contribution', models.TextField(blank=True, verbose_name='Вклад в работу')),
                ('corresponding_author', models.BooleanField(default=False, verbose_name='Автор для корреспонденции')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Автор доклада',
                'verbose_name_plural': 'Авторы докладов',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AuthorRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название роли')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код роли')),
                ('description', models.TextField(blank=True, verbose_name='Описание роли')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основная роль')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Роль автора',
                'verbose_name_plural': 'Роли авторов',
            },
        ),
    ]
