# Generated by Django 5.2.10 on 2026-02-01 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
        ('talks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы'),
        ),
        migrations.AddField(
            model_name='authorreport',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_authorships', to='authors.author', verbose_name='Автор'),
        ),
        migrations.AddField(
            model_name='authorreport',
            name='report',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_reports', to='talks.report', verbose_name='Доклад'),
        ),
        migrations.AddField(
            model_name='authorreport',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_reports', to='authors.authorrole', verbose_name='Роль'),
        ),
        migrations.AlterUniqueTogether(
            name='authorreport',
            unique_together={('author', 'report')},
        ),
    ]
