# Generated by Django 5.2.10 on 2026-02-01 15:07

import talks.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='Название секции')),
                ('description', models.TextField(blank=True, verbose_name='Описание секции')),
                ('icon', models.CharField(default='📄', max_length=50, verbose_name='Иконка')),
                ('color', models.CharField(default='#4effff', max_length=20, verbose_name='Цвет')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Секция',
                'verbose_name_plural': 'Секции',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, verbose_name='Название доклада')),
                ('abstract', models.TextField(blank=True, help_text='Краткое описание доклада (200-500 слов)', null=True, verbose_name='Аннотация доклада')),
                ('report_file', models.FileField(help_text='Текст доклада в формате DOC, DOCX или PDF', upload_to=talks.models.report_file_path, verbose_name='Доклад (Word/PDF)')),
                ('presentation_file', models.FileField(blank=True, help_text='Презентация в формате PPT, PPTX или PDF', null=True, upload_to=talks.models.report_file_path, verbose_name='Презентация')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('review', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='draft', max_length=20, verbose_name='Статус')),
                ('keywords', models.CharField(blank=True, help_text='Ключевые слова через запятую', max_length=500, verbose_name='Ключевые слова')),
                ('doi', models.CharField(blank=True, max_length=100, verbose_name='DOI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(related_name='reports', through='authors.AuthorReport', to='authors.author', verbose_name='Авторы')),
            ],
            options={
                'verbose_name': 'Доклад',
                'verbose_name_plural': 'Доклады',
                'ordering': ['-created_at'],
            },
        ),
    ]
