# Generated by Django 5.2.10 on 2026-02-02 08:48

import django.db.models.deletion
import talks.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_initial'),
        ('talks', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('certificate_type', models.CharField(choices=[('participation', 'Сертификат участника'), ('winner', 'Грамота победителя'), ('diploma', 'Диплом'), ('thank_you', 'Благодарность')], default='participation', max_length=20, verbose_name='Тип документа')),
                ('place', models.PositiveIntegerField(blank=True, null=True, verbose_name='Место (если призовое)')),
                ('nomination', models.CharField(blank=True, max_length=200, verbose_name='Номинация')),
                ('file', models.FileField(upload_to=talks.models.certificate_file_path, verbose_name='Файл документа')),
                ('issued_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выдачи')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликован')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='authors.author', verbose_name='Автор')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_certificates', to=settings.AUTH_USER_MODEL, verbose_name='Кем выдан')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='talks.report', verbose_name='Доклад')),
            ],
            options={
                'verbose_name': 'Грамота/сертификат',
                'verbose_name_plural': 'Грамоты/сертификаты',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('minor_revisions', 'Незначительные доработки'), ('major_revisions', 'Значительные доработки'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20, verbose_name='Статус рецензии')),
                ('comment_for_author', models.TextField(help_text='Конструктивные замечания и предложения для автора', verbose_name='Комментарий для автора')),
                ('comment_for_committee', models.TextField(blank=True, help_text='Внутренний комментарий для программного комитета', verbose_name='Комментарий для комитета')),
                ('score_originality', models.PositiveSmallIntegerField(default=3, verbose_name='Оригинальность (1-5)')),
                ('score_relevance', models.PositiveSmallIntegerField(default=3, verbose_name='Актуальность (1-5)')),
                ('score_methodology', models.PositiveSmallIntegerField(default=3, verbose_name='Методология (1-5)')),
                ('score_presentation', models.PositiveSmallIntegerField(default=3, verbose_name='Презентация (1-5)')),
                ('score_quality', models.PositiveSmallIntegerField(default=3, verbose_name='Качество (1-5)')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='Рецензия подтверждена')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='talks.report', verbose_name='Доклад')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Рецензент')),
            ],
            options={
                'verbose_name': 'Рецензия',
                'verbose_name_plural': 'Рецензии',
                'unique_together': {('report', 'reviewer')},
            },
        ),
    ]
