# Generated by Django 5.2.10 on 2026-02-03 12:25

import django.db.models.deletion
import talks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_initial'),
        ('talks', '0003_certificate_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='color',
        ),
        migrations.AddField(
            model_name='section',
            name='date',
            field=models.DateField(default=talks.models.default_date, help_text='Дата проведения секции', verbose_name='Дата проведения'),
        ),
        migrations.AddField(
            model_name='section',
            name='jury_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_sections', to='authors.author', verbose_name='Председатель жюри'),
        ),
        migrations.AddField(
            model_name='section',
            name='jury_members',
            field=models.ManyToManyField(blank=True, related_name='jury_sections', to='authors.author', verbose_name='Члены жюри'),
        ),
        migrations.AddField(
            model_name='section',
            name='location',
            field=models.CharField(default='', help_text='Аудитория или зал', max_length=200, verbose_name='Место проведения'),
        ),
        migrations.AddField(
            model_name='section',
            name='time',
            field=models.TimeField(default=talks.models.default_time, help_text='Время начала секции', verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(verbose_name='Описание секции'),
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.ImageField(help_text='Изображение для секции (рекомендуемый размер: 200x200px)', upload_to=talks.models.section_icon_path, verbose_name='Иконка/логотип секции'),
        ),
    ]
