# Generated by Django 5.2.10 on 2026-02-03 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0004_remove_section_color_section_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, help_text='Дата проведения секции', verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='section',
            name='jury_chairman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chairman_sections', to=settings.AUTH_USER_MODEL, verbose_name='Председатель жюри'),
        ),
        migrations.AlterField(
            model_name='section',
            name='jury_members',
            field=models.ManyToManyField(blank=True, related_name='jury_sections', to=settings.AUTH_USER_MODEL, verbose_name='Члены жюри'),
        ),
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now, help_text='Время начала секции', verbose_name='Время начала'),
        ),
    ]
