# Generated by Django 5.2.10 on 2026-02-04 07:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0005_alter_section_date_alter_section_jury_chairman_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='jury_members',
        ),
        migrations.CreateModel(
            name='JuryMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=150, verbose_name='Отчество')),
                ('organization', models.CharField(blank=True, max_length=300, verbose_name='Организация')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('academic_degree', models.CharField(blank=True, max_length=100, verbose_name='Ученая степень')),
                ('academic_title', models.CharField(blank=True, max_length=100, verbose_name='Ученое звание')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Телефон')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jury_members_list', to='talks.section', verbose_name='Секция')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jury_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь системы')),
            ],
            options={
                'verbose_name': 'Член жюри',
                'verbose_name_plural': 'Члены жюри',
                'ordering': ['order', 'last_name', 'first_name'],
                'unique_together': {('section', 'user')},
            },
        ),
    ]
