# Generated by Django 5.2.10 on 2026-02-06 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0006_remove_section_jury_members_jurymember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='authors',
        ),
    ]
