# Generated by Django 5.2.10 on 2026-02-08 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0007_remove_report_authors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Рецензия', 'verbose_name_plural': 'Рецензии'},
        ),
        migrations.AddField(
            model_name='report',
            name='needs_revision',
            field=models.BooleanField(default=False, verbose_name='Требуются доработки'),
        ),
        migrations.AddField(
            model_name='report',
            name='resubmitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='revision_notes',
            field=models.TextField(blank=True, help_text='Замечания, которые необходимо исправить', verbose_name='Замечания по доработке'),
        ),
        migrations.AddField(
            model_name='review',
            name='is_visible_to_author',
            field=models.BooleanField(default=False, verbose_name='Видна автору'),
        ),
        migrations.AddField(
            model_name='review',
            name='visible_to_author_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('review', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено'), ('revisions_required', 'Требуются доработки'), ('resubmitted', 'Подано повторно')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_methodology',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Методология (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_originality',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Оригинальность (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_presentation',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Презентация (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_quality',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Качество (1-5)'),
        ),
        migrations.AlterField(
            model_name='review',
            name='score_relevance',
            field=models.PositiveSmallIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')], default=3, verbose_name='Актуальность (1-5)'),
        ),
    ]
