# Generated by Django 5.2.10 on 2026-02-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0008_alter_review_options_report_needs_revision_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='comment_for_author',
        ),
        migrations.RemoveField(
            model_name='review',
            name='comment_for_committee',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_methodology',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_originality',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_presentation',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_quality',
        ),
        migrations.RemoveField(
            model_name='review',
            name='score_relevance',
        ),
        migrations.AddField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, help_text='Ваши замечания и предложения для автора', verbose_name='Комментарий рецензента'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('accepted', 'Принят'), ('revisions_required', 'Требуются доработки')], default='pending', max_length=20, verbose_name='Статус рецензии'),
        ),
    ]
