# Generated by Django 5.2.10 on 2026-02-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0009_remove_review_comment_for_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='needs_revision',
        ),
        migrations.RemoveField(
            model_name='report',
            name='revision_notes',
        ),
        migrations.AddField(
            model_name='report',
            name='admin_comment',
            field=models.TextField(blank=True, help_text='Замечания и предложения для авторов', verbose_name='Комментарий администратора'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
