# Generated by Django 5.2.10 on 2026-02-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0010_remove_report_needs_revision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='revision_description',
            field=models.TextField(blank=True, help_text='Что было исправлено в докладе после замечаний', verbose_name='Описание внесенных изменений'),
        ),
    ]
