# Generated by Django 5.2.10 on 2026-02-18 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0011_report_revision_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('submitted', 'Подано'), ('review', 'На рассмотрении'), ('approved', 'Допущено до очного тура'), ('rejected', 'Отклонено'), ('revisions_required', 'Требуются доработки'), ('resubmitted', 'Подано повторно')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
