# Generated by Django 5.2.10 on 2026-02-20 12:49

import talks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talks', '0012_alter_report_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='media_archive',
            field=models.FileField(blank=True, help_text='ZIP или RAR архив с фотографиями и видео (макс. 50MB)', null=True, upload_to=talks.models.report_file_path, verbose_name='Архив с фото/видео'),
        ),
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('submitted', 'Подано'), ('review', 'На рассмотрении'), ('approved', 'Допущено до очного тура'), ('rejected', 'Отклонено'), ('revisions_required', 'Требуются доработки'), ('resubmitted', 'Подано повторно')], default='draft', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='section',
            name='icon',
            field=models.ImageField(blank=True, help_text='Изображение для секции (рекомендуемый размер: 200x200px)', null=True, upload_to=talks.models.section_icon_path, verbose_name='Иконка/логотип секции'),
        ),
    ]
